src/app/page.tsx
=> test: 풀리퀘스트 테스트

.prettierrc, .vscode/settings.json, components.json, package-lock.json, package.json, public/mockServiceWorker.js, src/app/api/exam/route.ts, src/app/globals.css, src/app/layout.tsx, src/components/ui/button.tsx, src/lib/utils.ts, tailwind.config.ts
=> chore: 라이브러리 설치

src/app/page.tsx
=> test: 병합 테스트

package-lock.json
=> fix: 스토리북 충돌 해결

src/components/common/Atoms/buttons/NotiBellButton.tsx
=> doc: notibell icon doc 추가

tailwind.config.ts
=> style: tailwind config 추가함.

src/app/globals.scss, src/components/ui/progress.stories.tsx
=> dfeat: progress gradient 디자인 요구사항에 맞게 추가

.env.development, .env.production, .vscode/tasks.json, src/app/api/mock/exam/route.ts, src/app/api/mock/route.ts, src/app/layout.tsx, src/mocks/MswProvider.tsx, src/mocks/browser.ts, src/mocks/handlers.ts, src/mocks/http.ts, src/services/api.ts, start.ps1
close :  #36
msw + express 사용해서 mock서버 구현
=> Feat: msw 환경설정

package-lock.json, package.json, src/app/globals.scss, src/asset/Icons/dash-line.svg, src/asset/Icons/index.tsx, src/components/common/Monocles/progress-bar/ContractProgress.stories.tsx, src/components/common/Monocles/progress-bar/ContractProgress.tsx, src/components/ui/progress.stories.tsx
close :  #38
feat: 계약기간, 슬래시 progressbar 추가
https://66421fd64f35d30603e16002-kzqeethqre.chromatic.com/?path=/docs/monocles-progressbar-contractprogress--docs
https://66421fd64f35d30603e16002-kzqeethqre.chromatic.com/?path=/story/ui-progressbar-progress--slash-progress
=> feat: 계약기간, 슬래시 progressbar 추가

src/app/(after-login)/room/@CategoryRating/page.tsx, src/app/(after-login)/room/@Overview/page.tsx, src/app/(after-login)/room/@RatingManagement/page.tsx, src/app/(after-login)/room/@RatingTrend/page.tsx, src/app/(after-login)/room/default.tsx, src/app/(after-login)/room/layout.tsx
close : #48 
- 초기 설정 세팅
- 서버 사이드에서 URL을 확인하는 것은 어렵다고 판단됨
=> feat: 호실 페이지 초기 설정

src/app/(after-login)/room/@Overview/_component/ContractInfoClientComp.tsx, src/app/(after-login)/room/@Overview/_component/ContractInfoServerComp.tsx, src/app/(after-login)/room/@Overview/_component/ContractRentInfo.tsx, src/app/(after-login)/room/@Overview/page.tsx, src/components/common/Monocles/progress-bar/ContractProgress.stories.tsx, src/components/common/Monocles/progress-bar/ContractProgress.tsx, src/utils/index.ts
close : #47 
```
// 경과된 진행율 계산 함수
export const calculateDateProgress = (start: Date, end: Date, current: Date | undefined): number => {
if (!current) current = new Date();
// 1. 기간 계산 (밀리초 단위로 계산)
const totalTime = end.getTime() - start.getTime(); // 전체 기간
const elapsed = current.getTime() - start.getTime(); // 현재까지의 경과 기간
// 2. 진행률 계산
const progress = (elapsed / totalTime) * 100; // 진행률 계산 (백분율로 표현)
// 3. 정수로 return
return Math.round(progress); // 정수로 반올림
};
```
```tsx
export const formatDateToYYYY_MM_DD = (date: Date | undefined): string => {
if (!date) return '----.--.--';
return dayjs(date).format('YYYY.MM.DD');
};
```
@Lamyzm 
ContractProgress에서 cn -> clsx로 변경했습니다.
twMerge에 text-custom-color, text-custom-font 둘이 충돌나서 하나를 없애는 버그가 있습니다.
이외에도 종종 이렇게 없애는 것 같은데, 내일 데일리스크럼 때 공유드리겠습니다.
=> feat: 계약 정보 섹션 구현

src/app/(after-login)/dashboard/@MainRoomCompare/loading.tsx, src/app/(after-login)/room/@Overview/_component/RatingCompareComp.tsx, src/app/(after-login)/room/@Overview/page.tsx, src/app/(after-login)/room/layout.tsx, src/components/charts/MainVerticalBarChart.tsx, src/components/charts/bar-chart/SingleCategoryVerticalBarChart.stories.tsx, src/components/charts/bar-chart/SingleCategoryVerticalBarChart.tsx, src/components/common/Atoms/badge/IndicateBadge.tsx
close :  #49 
RatingCompareComp 154줄 
zod로 값검증후 값이 없으면 - 처리했습니다
차트는 값이없으면 아에 표시되지않는데 이부분 개선필요할듯함
=> feat: 임대비교지표 섹션 구현

next.config.mjs, package-lock.json, package.json, src/components/charts/CustomTooltip.tsx, src/components/charts/bar-chart/ScoreTrendChart.stories.tsx, src/components/charts/bar-chart/ScoreTrendChart.tsx, src/components/charts/line-chart/ScoreTrendChart.tsx
close : #52
스토리북 만들어놨습니다 참고하세용
=> feat: 히스토그램 바차트 구현

package-lock.json, package.json
close : #78 
- devDep에 esbuild 추가하여 storybook 사용시 발생하는 esbuild
-  버그 수정함.
참고 자료 : https://github.com/evanw/esbuild/issues/1646
=> fix: esbuild 에러 수정

src/lib/utils.ts
close : #80
- 메인테이너의 답변대로 extend 하여 classGroup에 font-size text-overline을 추가함.
- 다른 폰트사이즈, 컬러등의 추가 대응이 필요할 경우 그때마다 추가하여 사용
=> fix: cn twMerge 버그 수정

package-lock.json, src/app/(after-login)/room/@Overview/page.tsx, src/app/(after-login)/room/@RatingManagement/_component/RatingManagementServerComp.tsx, src/app/(after-login)/room/@RatingTrend/page.tsx, src/components/charts/CustomTooltip.tsx, src/components/charts/line-chart/ScoreTrendChart.tsx, src/components/common/Monocles/progress-bar/ReviewTrackProgress.tsx
close :  #55
내호실 점수변화 한눈에 보기 섹션
추후 리사이즈 옵저버 사용해서 모바일 세밀히 대응할 예정
=> feat: 호실 1년 점수변화 라인차트

src/app/(after-login)/room/@CategoryRating/page.tsx, src/asset/Icons/index.tsx, src/components/charts/bar-chart/ScoreTrendChart.tsx
=> Feat/room categoryrating/#54

src/app/(after-login)/room/@CategoryRating/page.tsx, src/app/(after-login)/room/@Overview/_component/ContractInfoServerComp.tsx, src/app/(after-login)/room/@Overview/_component/MyRoomScoreServerComp.tsx, src/app/(after-login)/room/@Overview/_component/RatingCompareComp.tsx, src/app/(after-login)/room/@Overview/page.tsx, src/app/(after-login)/room/@RatingManagement/_component/RatingManagementClientComp.tsx, src/app/(after-login)/room/@SelectBox/page.tsx, src/app/(after-login)/room/layout.tsx, src/components/common/Atoms/seletbox/Selectbox.tsx, src/types/common/selectbox.ts
close : #56
페이지 모바일 대응 및 레이아웃작업, 인풋추가
=> feat: 호실관리페이지 레이아웃, 모바일대응

src/app/(after-login)/rating-detail/_component/RatingDetailPagination.tsx, src/components/common/Atoms/seletbox/Selectbox.tsx, src/components/common/Organisms/navigation/DesktopGNB.tsx, src/types/common/selectbox.ts
close : 
- key prop이 누락되어 발생한 에러 수정
- Select onChange 타입 수정 후 DesktopGNB에서 발생한 에러 수정
=> fix: 상세 평가 내용 이후 발생한 빌드 버그 수정

src/middleware.tsx, src/services/api.tsx, src/services/intercepter.ts, src/types/auth/index.tsx
=> feat: 유저 세션검증 및 미들웨어로 유저 role에 따른 리디렉션

src/app/(after-login)/dashboard/@MainRoomCompare/page.tsx, src/app/(after-login)/dashboard/@Overview/page.tsx, src/app/(after-login)/dashboard/layout.tsx, src/app/(after-login)/layout.tsx, src/components/common/Organisms/navigation/DesktopGNB.tsx, src/components/common/Organisms/navigation/MobileGNB.tsx, tailwind.config.ts
=> style: gnb 스타일 변경
